### ISSUE TITLE
Toast引用求助

### ISSUE THREAD

**Issue by peachQAQ** [youzan/vant-weapp#1466]
路径是没有错的，button和col row都能正确引用。
</br>
//json文件
```
{
  "usingComponents": {
    "van-toast": "../../miniprogram_npm/vant-weapp/toast/index",
    "van-button": "../../miniprogram_npm/vant-weapp/button/index",
    "van-row": "../../miniprogram_npm/vant-weapp/row/index",
    "van-col": "../../miniprogram_npm/vant-weapp/col/index"
  }
}
```
//wxml页面
```
<text>页面</text>
<van-button bind:click="showToast"type="default">显示</van-button>
<van-toast id="van-toast" />
```
//js页面
```
import Toast from '../../miniprogram_npm/vant-weapp/toast/index';

Page({
......
showToast() {
    Toast("hello");
  }
})
```

报错：
```
(0 , _index2.default) is not a function; [Component] Event Listener Error @ miniprogram_npm/vant-weapp/button/index#(anonymous)
TypeError: (0 , _index2.default) is not a function
    at H.showToast (http://127.0.0.1:11735/appservice/pages/page_admin/page_admin.js:57:25)
    at H.A.u.(anonymous function).(anonymous function).u.addListener.capture (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:914435)
    at r.safeCallback (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:758737)
    at r.call (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:758630)
    at n (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:761627)
    at http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:762209
    at p (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:761174)
    at Function.c.dispatchEvent (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:762106)
    at Function.c.triggerEvent (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:762309)
    at n.w.triggerEvent (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:838633)
```
估计指向的是showToast( ) 内的 Toast('hello')

**Comment by peachQAQ** [comment]
新增：
采用Notify后，Notify是可以弹出来的。
```
  showToast() {
    Toast("hello");
  },

  showNotify() {
    Notify("通知内容");
  }
```
```
<view>
  <van-button bind:click="showToast" type="default">Toast</van-button>
  <van-toast id="van-toast" />
   <van-button bind:click="showNotify" type="default">Notify</van-button>
  <van-notify id="van-notify" />
</view>
```

**Comment by rex-zsd** [comment]
`import Toast from '../../miniprogram_npm/vant-weapp/toast/index';`
这部分有问题
import Toast from '../../miniprogram_npm/vant-weapp/toast/toast';
index内是组件，不是方法

**Comment by peachQAQ** [comment]
> `import Toast from '../../miniprogram_npm/vant-weapp/toast/index';`
> 这部分有问题
> `import Toast from '../../miniprogram_npm/vant-weapp/toast/toast';`
> index内是组件，不是方法

啊！谢谢您！对不起，使用时不认真，给您添麻烦了。
