### ISSUE TITLE
没有热更新，在重启dev（npm run dev)的情况下报错

### ISSUE THREAD

**Issue by Panseng** [youzan/vant-weapp#1699]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果
npm run dev后，打开微信小程序开发工具，然后只对button的背景颜色做更改，重新npm run dev报错：（关闭小程序开发工具重新npm run dev不再报错，正常运行）

`E:\Download\vant-weapp-dev\node_modules\fs-extra\lib\remove\rimraf.js:262
      throw er
      ^
Error: ENOTEMPTY: directory not empty, rmdir 'E:\Download\vant-weapp-dev\example\dist\mixins'
    at Object.fs.rmdirSync (fs.js:846:18)
    at rmkidsSync (E:\Download\vant-weapp-dev\node_modules\fs-extra\lib\remove\rimraf.js:304:27)
    at rmdirSync (E:\Download\vant-weapp-dev\node_modules\fs-extra\lib\remove\rimraf.js:281:7)
    at rimrafSync (E:\Download\vant-weapp-dev\node_modules\fs-extra\lib\remove\rimraf.js:252:7)
    at options.readdirSync.forEach.f (E:\Download\vant-weapp-dev\node_modules\fs-extra\lib\remove\rimraf.js:291:39)
    at Array.forEach (<anonymous>)
    at rmkidsSync (E:\Download\vant-weapp-dev\node_modules\fs-extra\lib\remove\rimraf.js:291:26)
    at rmdirSync (E:\Download\vant-weapp-dev\node_modules\fs-extra\lib\remove\rimraf.js:281:7)
    at Object.rimrafSync [as removeSync] (E:\Download\vant-weapp-dev\node_modules\fs-extra\lib\remove\rimraf.js:252:7)
    at Object.<anonymous> (E:\Download\vant-weapp-dev\build\dev.js:9:4)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
`

**截图**
如果是 UI 问题，请提供具体截图
![image](https://user-images.githubusercontent.com/48272139/59430224-48009a80-8e14-11e9-9b72-4703202656ca.png)

**核心代码**
请提供使用组件的核心代码

```js
```

```wxml
```

**环境**
处于源码更改阶段，在windows 10企业版
 - 设备: 
 - 基础库版本:
 - Vant Weapp 版本: 0.5.14

**Comment by rex-zsd** [comment]
微信开发者工具的问题，重启开发者工具可解决
