### ISSUE TITLE
基础库很多都没有？比如那个9宫格

### ISSUE THREAD

**Issue by sinhang** [youzan/vant-weapp#2274]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by sinhang** [comment]
VM1750:1 jsEnginScriptError
Component is not found in path "miniprogram_npm/vant-weapp/grid/index" (using by "pages/index/index");onAppRoute
Error: Component is not found in path "miniprogram_npm/vant-weapp/grid/index" (using by "pages/index/index")
    at q (http://127.0.0.1:26272/appservice/__dev__/WAService.js:1:1351064)
    at q (http://127.0.0.1:26272/appservice/__dev__/WAService.js:1:1351268)
    at http://127.0.0.1:26272/appservice/__dev__/WAService.js:1:1372151
    at Module.Le (http://127.0.0.1:26272/appservice/__dev__/WAService.js:1:1372730)
    at Function.value (http://127.0.0.1:26272/appservice/__dev__/WAService.js:1:1456018)
    at Tt (http://127.0.0.1:26272/appservice/__dev__/WAService.js:1:1471900)
    at http://127.0.0.1:26272/appservice/__dev__/WAService.js:1:1476166
    at At (http://127.0.0.1:26272/appservice/__dev__/WAService.js:1:1476659)
    at Function.<anonymous> (http://127.0.0.1:26272/appservice/__dev__/WAService.js:1:1480135)
    at i.<anonymous> (http://127.0.0.1:26272/appservice/__dev__/WAService.js:1:1448957)

**Comment by chenjiahan** [comment]
请升级到最新的 1.0.0-beta.2 版本
