### ISSUE TITLE
[Bug Report] 关于 goods-action-button 的一些报错信息

### ISSUE THREAD

**Issue by charescape** [youzan/vant-weapp#2890]
### 设备
ios/android

### VantWeapp 版本
1.1.0-beta.2

### 基础库版本
最新

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/goods-action

### 描述问题
```
Cannot read property 'children' of null; [Component] Lifetime Method Error @ miniprogram_npm/@vant/weapp/goods-action-button/index#mounted
TypeError: Cannot read property 'children' of null
at me.updateStyle (https://miniprogram:///miniprogram_npm/@vant/weapp/goods-action-button/index.js:34:34)
at me.mounted (https://miniprogram:///miniprogram_npm/@vant/weapp/goods-action-button/index.js:26:14)
at r.safeCallback (https://lib/WASubContext.js:2:1313788)
at r.call (https://lib/WASubContext.js:2:1313681)
at n.M.triggerLifeTime (https://lib/WASubContext.js:2:1357287)
at https://lib/WASubContext.js:2:1406366
at Object.r.safeCallback (https://lib/WASubContext.js:2:1313788)
at a.value (https://lib/WASubContext.js:2:1486823)
at https://lib/WASubContext.js:2:1484470
at r (https://lib/WASubContext.js:2:1385751)
```

```
null is not an object (evaluating 'this.parent.children'); [Component] Lifetime Method Error @ miniprogram_npm/@vant/weapp/goods-action-button/index#mounted
updateStyle@https://miniprogram:///miniprogram_npm/@vant/weapp/goods-action-button/index.js:34:27
mounted@https://miniprogram:///miniprogram_npm/@vant/weapp/goods-action-button/index.js:26:14
safeCallback@https://lib/WASubContext.js:2:1314341
call@https://lib/WASubContext.js:2:1314230
triggerLifeTime@https://lib/WASubContext.js:2:1357839
https://lib/WASubContext.js:2:1406929
safeCallback@https://lib/WASubContext.js:2:1314341
value@https://lib/WASubContext.js:2:1487383
https://lib/WASubContext.js:2:1485041
r@https://lib/WASubContext.js:2:1386300
https://lib/WASubContext.js:2:1386422
https://lib/WASubContext.js:2:598600
https://lib/WAServiceMainContext.js:2:224427
_@https://lib/WAServiceMainContext.js:2:77597
```

**Comment by rex-zsd** [comment]
没有使用代码确定不了具体问题。
看报错信息是使用姿势的问题，goods-action-button是需要嵌套在goods-action内使用的哈。
