### ISSUE TITLE
下载下来的源码 执行build:lib 编译TS时候报错

### ISSUE THREAD

**Issue by duyu123** [youzan/vant-weapp#3081]
14:25:58] 'compileTs' errored after 13 s
[14:25:58] Error: Command failed: npx tsc -p E:\studyspace\vant-weapp-dev\tsconfig.json

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at ChildProcess.EventEmitter.emit (domain.js:499:23)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:499:23)
    at Pipe.<anonymous> (net.js:658:12)
[14:25:58] 'buildEs' errored after 14 s
[14:25:58] The following tasks did not complete: compileLess, <parallel>, copy, copy, copy
[14:25:58] Did you forget to signal async completion?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by rex-zsd** [comment]
看了一下是依赖的`miniprogram-api-typings`在构件时报错了，我们修复一下哈。
