### ISSUE TITLE
[Bug Report] van-goods-action报错

### ISSUE THREAD

**Issue by 1sm23** [youzan/vant-weapp#3138]
### 设备
IDE

### VantWeapp 版本
1.2.2

### 基础库版本
2.10.4

### 请提供核心代码片段链接
https://gist.github.com/1sm23/2f1c31fcd4f17d0e963be021956aebd6

### 描述问题
```bash
VM19300:1 thirdScriptError
Cannot read property 'children' of null; [Component] Lifetime Method Error @ miniprogram_npm/@vant/weapp/goods-action-button/index#mounted
TypeError: Cannot read property 'children' of null
    at Se.updateStyle (http://127.0.0.1:64122/appservice/miniprogram_npm/@vant/weapp/goods-action-button/index.js:43:28)
    at Se.mounted (http://127.0.0.1:64122/appservice/miniprogram_npm/@vant/weapp/goods-action-button/index.js:35:10)
    at r.safeCallback (http://127.0.0.1:64122/appservice/__dev__/WAService.js:2:1467232)
    at r.call (http://127.0.0.1:64122/appservice/__dev__/WAService.js:2:1467125)
    at n.M.triggerLifeTime (http://127.0.0.1:64122/appservice/__dev__/WAService.js:2:1510731)
    at http://127.0.0.1:64122/appservice/__dev__/WAService.js:2:1560170
    at Object.r.safeCallback (http://127.0.0.1:64122/appservice/__dev__/WAService.js:2:1467232)
    at a.value (http://127.0.0.1:64122/appservice/__dev__/WAService.js:2:1640227)
    at http://127.0.0.1:64122/appservice/__dev__/WAService.js:2:1637874
    at r (http://127.0.0.1:64122/appservice/__dev__/WAService.js:2:1538494)
```

**Comment by rex-zsd** [comment]
wxml复制过来没有复现，这个错误出现的原因是goods-action-button渲染完成了，但是goods-action还未渲染。
有使用什么小程序框架吗？可能会对组件初始化的逻辑有影响

**Comment by rex-zsd** [comment]
我们可以做个兼容让代码不报错，但是这个场景下，按钮应该是没法正常渲染的。

**Comment by 1sm23** [comment]
> wxml复制过来没有复现，这个错误出现的原因是goods-action-button渲染完成了，但是goods-action还未渲染。
> 有使用什么小程序框架吗？可能会对组件初始化的逻辑有影响

没有使用其他框架 , 原生开发

**Comment by 1sm23** [comment]
> 我们可以做个兼容让代码不报错，但是这个场景下，按钮应该是没法正常渲染的。

感谢 #3145 这个起作用
