### ISSUE TITLE
[Bug Report] Cannot read property 'vanPageScroller' of undefined

### ISSUE THREAD

**Issue by superlbr** [youzan/vant-weapp#4230]
### 设备
Redmi M2007J3SC

### VantWeapp 版本
1.6.9-beta.2

### 基础库版本
2.17.0

### 描述问题
 MiniProgramError Cannot read property 'vanPageScroller' of undefined 
TypeError: Cannot read property 'vanPageScroller' of undefined 
at vt.detached (https://usr/app-service.js:6296:603) 
at o.safeCallback (https://lib/WASubContext.js:2:2226651) 
at o.call (https://lib/WASubContext.js:2:2226436) 
at t (https://lib/WASubContext.js:2:2242924)

**Comment by wiexin** [comment]
官方不修复吗

**Comment by shenjingnan** [comment]
重复issue #4327
