### ISSUE TITLE
[Bug Report] 小程序使用组件报错

### ISSUE THREAD

**Issue by Memoryzzzzzz** [youzan/vant-weapp#4637]
### 设备 / 浏览器
安卓

### Vant 版本
2.12.34

### Vue 版本
3.2.22

### 重现链接
<a href="http://www.test.com" target="_blank">http://www.test.com</a>

### 描述问题
Cannot read property \'vanPageScroller\' of undefined
TypeError: Cannot read property \'vanPageScroller\' of undefined
at Li.detached (https://miniprogram_npm/@vant/weapp/mixins/page-scroll.js:29:21)
at i.safeCallback (https://lib/WASubContext.js:2:2137215)
at i.call (https://lib/WASubContext.js:2:2137000)
at t (https://lib/WASubContext.js:2:2155152)
at t (https://lib/WASubContext.js:2:2155039)
at t (https://lib/WASubContext.js:2:2155039)
at t (https://lib/WASubContext.js:2:2155074)
at f (https://lib/WASubContext.js:2:2155384)
at Function.d.pretendDetached (https://lib/WASubContext.js:2:2167268)
at Module.go (https://lib/WASubContext.js:2:2322275)

**Comment by shenjingnan** [comment]
1.10.0已发布

**Comment by chenjiahan** [comment]
@nemo-shen 后续已经有关联 PR 的 issue 可以打个标记哈，免得忘了

![image](https://user-images.githubusercontent.com/7237365/146861478-186823ae-f12e-4f6c-860c-f8702312c797.png)
