### ISSUE TITLE
npm run dev 失败

### ISSUE THREAD

**Issue by Zzzzzzzzero** [youzan/vant-weapp#4745]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
npm run dev运行失败

错误提示：
internal/modules/cjs/loader.js:1253
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: E:\workspace\vant-weapp\node_modules\@vant\cli\lib\index.js
require() of ES modules is not supported.
require() of E:\workspace\vant-weapp\node_modules\@vant\cli\lib\index.js from E:\workspace\vant-weapp\build\dev.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from E:\workspace\vant-weapp\node_modules\@vant\cli\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1253:13)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (E:\workspace\vant-weapp\build\dev.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14) {
  code: 'ERR_REQUIRE_ESM'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @vant/weapp@1.10.1 dev: `node build/dev.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @vant/weapp@1.10.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2022-01-11T10_09_36_771Z-debug.log

**Comment by shenjingnan** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

**Comment by dingdr** [comment]
我也碰到这样的问题，请问怎么解决

**Comment by Zzzzzzzzero** [comment]
> 我也碰到这样的问题，请问怎么解决

我发现我那个是因为@vant/cli版本的问题，你可以试一下指定版本安装，他会默认安装4.0.0-rc.5版本的，rc.x这个版本的貌似都会有问题，避开这几个版本试试
