### ISSUE TITLE
[Bug Report] npm run dev 运行失败

### ISSUE THREAD

**Issue by Zzzzzzzzero** [youzan/vant-weapp#4748]
### 设备
window10

### VantWeapp 版本
1.10.1

### 基础库版本
2.6.5

### 请提供核心代码片段链接
https://gist.github.com/Zzzzzzzzero/aff00d6489d3f47fa2d831262627b19c

### 描述问题
npm install
npm run dev 无法运行

**Comment by shenjingnan** [comment]
你是要提PR吗？

**Comment by nemo-shen** [comment]
你是要提PR吗？

**Comment by nemo-shen** [comment]
你是要提PR吗？

**Comment by Zzzzzzzzero** [comment]
不是，我是npm run dev的时候失败了，无法启动

**Comment by Zzzzzzzzero** [comment]
> 你是要提PR吗？

不是，我是npm run dev的时候失败了，无法启动

**Comment by busyfree** [comment]
npm run dev 错误日志 
```shell
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/17.3.1/bin/node',
1 verbose cli   '/npm/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v17.3.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @vant/weapp@1.10.2~predev: @vant/weapp@1.10.2
6 info lifecycle @vant/weapp@1.10.2~dev: @vant/weapp@1.10.2
7 verbose lifecycle @vant/weapp@1.10.2~dev: unsafe-perm in lifecycle true
9 verbose lifecycle @vant/weapp@1.10.2~dev: CWD: /codes/nodejs/vant-weapp
10 silly lifecycle @vant/weapp@1.10.2~dev: Args: [ '-c', 'node build/dev.js' ]
11 silly lifecycle @vant/weapp@1.10.2~dev: Returned: code: 1  signal: null
12 info lifecycle @vant/weapp@1.10.2~dev: Failed to exec dev script
13 verbose stack Error: @vant/weapp@1.10.2 dev: `node build/dev.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/npm/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (node:events:390:28)
13 verbose stack     at ChildProcess.<anonymous> (/npm/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (node:events:390:28)
13 verbose stack     at maybeClose (node:internal/child_process:1062:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
14 verbose pkgid @vant/weapp@1.10.2
15 verbose cwd /codes/nodejs/vant-weapp
16 verbose Darwin 21.2.0
17 verbose argv "/usr/local/Cellar/node/17.3.1/bin/node" "/npm/bin/npm" "run" "dev"
18 verbose node v17.3.1
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error @vant/weapp@1.10.2 dev: `node build/dev.js`
22 error Exit status 1
23 error Failed at the @vant/weapp@1.10.2 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
- 复制外面的dist目录到 example里面
- 修复 app.json 里面的 usingComponents 数组里面的错误路径，所有的路径都多了 /demo/ 目录
- 再编译就OK了。但是点击进去的页面就样式有问题了。看下面截图
![image](https://user-images.githubusercontent.com/504251/150640197-17b68d6e-6c8f-440e-88fc-fd4c3dc1d701.png)
![image](https://user-images.githubusercontent.com/504251/150640207-eba9c2f4-2620-477a-b486-f94ac2956fee.png)

**Comment by landluck** [comment]
现在最新的版本没有发现这个问题，如还有问题辛苦重新提个issue
