### ISSUE TITLE
示例代码 运行 npm run dev 报错 （win）

### ISSUE THREAD

**Issue by linming1987** [youzan/vant-weapp#4937]
Finished 'copy' after 4.46 s

..\packages\common\utils.ts(41,7): error TS2367: This condition will always return 'false' since the types '"ios" | "android" | "windows" | "mac"' and '"devtools"' have no overlap.

TypeScript: 1 semantic error

TypeScript: emit succeeded (with errors)

[01:04:51]
'compileTs' errored after 9.87 s
[01:04:51] Error: TypeScript: Compilation failed
    at Output.mightFinish (G:\web\4\vant-weapp\node_modules\_gulp-typescript@6.0.0-alpha.1@gulp-typescript\release\output.js:131:43)
    at G:\web\4\vant-weapp\node_modules\_gulp-typescript@6.0.0-alpha.1@gulp-typescript\release\output.js:66:22

[01:04:51]
'buildExample' errored after 14 s

**Comment by linming1987** [comment]
output.js 注释掉131行 示例就可以运行
       // if (reporter.countErrors(this.result) !== 0) {
        //     this.streamFull.emit('error', new Error("TypeScript: Compilation failed"));
        // }
