### ISSUE TITLE
npm run dev fail

### ISSUE THREAD

**Issue by nobita0522** [youzan/vant-weapp#5116]
try to build in localhost,then an error occur when run 'npm run dev'
below is the detail error message

Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm (/Users/mac/Downloads/vant-weapp/node_modules/source-map/lib/read-wasm.js:8:13)
    at wasm (/Users/mac/Downloads/vant-weapp/node_modules/source-map/lib/wasm.js:25:16)
    at /Users/mac/Downloads/vant-weapp/node_modules/source-map/lib/source-map-consumer.js:264:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by nobita0522** [comment]
help wanted.thanks

**Comment by landluck** [comment]
Switch the nodejs version to v16
