### ISSUE TITLE
VM5531:1 thirdScriptError consloe is not defined; [Component] Event Listener Error @ dist/search/index#(anonymous) ReferenceError: consloe is not defined

### ISSUE THREAD

**Issue by meicuihui** [youzan/vant-weapp#522]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果
### 遇到问题:点击搜索时候，无法正常运行，报错如下
```
VM497:1 thirdScriptError
consloe is not defined; [Component] Event Listener Error @ dist/search/index#(anonymous)
ReferenceError: consloe is not defined
    at c.onSearch (http://127.0.0.1:11681/appservice/pages/index/index.js:16:5)
    at c.t.(anonymous function).(anonymous function).t.addListener.capture (http://127.0.0.1:11681/appservice/__dev__/WAService.js:20:6648)
    at r.safeCallback (http://127.0.0.1:11681/appservice/__dev__/WAService.js:17:14483)
    at r.call (http://127.0.0.1:11681/appservice/__dev__/WAService.js:17:14247)
    at n (http://127.0.0.1:11681/appservice/__dev__/WAService.js:17:16711)
    at http://127.0.0.1:11681/appservice/__dev__/WAService.js:17:17269
    at u (http://127.0.0.1:11681/appservice/__dev__/WAService.js:17:16256)
    at Function.r.dispatchEvent (http://127.0.0.1:11681/appservice/__dev__/WAService.js:17:17166)
    at Function.r.triggerEvent (http://127.0.0.1:11681/appservice/__dev__/WAService.js:17:17369)
    at a.u.triggerEvent (http://127.0.0.1:11681/appservice/__dev__/WAService.js:18:4484)
```
### 复现方式
1.  下载最新代码按照官网配置把dist目录放到项目里边
2. wxml文件代码
```
<van-search value="{{ value }}" show-action 
placeholder="请输入搜索关键词" bind:change="onChange" bind:search="onSearch" bind:cancel="onCancel" />
```
3.  json文件
```
{
  "usingComponents": {
    "van-search": "../../dist/search/index"
  }
}
```
4. js文件
```
//index.js
//获取应用实例

Page({
  data: {
    value: ''
  }, onChange(e) {
    console.log(e.detail+111)
    this.setData({
      value: e.detail
    });
  }, onSearch(event) {
    consloe.log("111111")
    if (event.detail) {
      wx.showToast({
        title: '搜索：' + event.detail,
        icon: 'none'
      });
    }
  },onCancel() {
    wx.showToast({
      title: '取消',
      icon: 'none'
    });
  }
 
})

```
5. 点击键盘的回车，出现报错
**截图**
如果是 UI 问题，请提供具体截图
![yx 1 ii3poj_za1zjff2if](https://user-images.githubusercontent.com/18278015/45194188-9630ae00-b284-11e8-96a7-2d78a48b446f.png)
![mn6xwoz2jh ukuc47 9ba](https://user-images.githubusercontent.com/18278015/45194191-97fa7180-b284-11e8-91cb-9de3950c925e.png)
![bg83mw xjbbwo2hi0 88 6](https://user-images.githubusercontent.com/18278015/45194192-99c43500-b284-11e8-944b-7a27cb16f29d.png)
![i 9cy1cmb_q 29 w41w65g](https://user-images.githubusercontent.com/18278015/45194205-a5176080-b284-11e8-91c9-87a34d0c52dd.png)

**环境**
 - 设备: windwos 10 
 - 基础库版本: 2018/9/7git clone下载的最新代码
 - Vant Weapp 版本: 2018/9/7 git clone下载的最新代码

**Comment by meicuihui** [comment]
谢谢
