### ISSUE TITLE
Loading 组件写在overlay组件中 会直接报错 

### ISSUE THREAD

**Issue by PeiJingbobo** [youzan/vant-weapp#5505]
### 重现链接

```
<van-overlay z-index="999999" show="{{ loading }}">
   
    <van-loading vertical="{{true}}"  color="#00b26a" size="24px">加载中...</van-loading>

</van-overlay>

```

这段代码运行在手机上会报错
```
SystemError (jsEnginScriptError)
Cannot read properties of undefined (reading 'index')
TypeError: Cannot read properties of undefined (reading 'index')
at u (common.app.js:1:31115)
at (common.app.js:1:31319)
    at Array.forEach (<anonymous>)
at (common.app.js:1:31296)
at (@vant/weapp/loading/index.appservice.js:1:1067)
at t.handleChildrenCreation (common.app.js:1:30528)
at (common.app.js:1:30777)
at (@vant/weapp/loading/index.appservice.js:1:746)
at t.handleChildrenCreation (common.app.js:1:30528)
at (common.app.js:1:30777)
```

还有一个
```
routeDone with a webviewId -988492509 that is not the current page
```

我想知道是因为什么,如何解决

### Vant Weapp 版本

1.10.21

### 描述一下你遇到的问题。

直接进入小程序白屏

### 重现步骤

直接进入页面

### 设备/浏览器

Xiaomi 12s Android 14 Weixin 8.0.40 基础库3.0.0

**Comment by PeiJingbobo** [comment]
这个bug只有扫微信预览码有,真机调试没有问题o(╥﹏╥)o

**Comment by johnsonwong666** [comment]
https://developers.weixin.qq.com/community/develop/article/doc/00000ede8cc11056617f117e056013
看一下是不是基础库的问题 社区上查看一下 
 手上的机器没有复现你那个Cannot read properties of undefined (reading 'index')  可以debug看一下
