### ISSUE TITLE
[Bug Report] field X(...).bem is not a function

### ISSUE THREAD

**Issue by tech-insq** [youzan/vant-weapp#5639]
### 重现链接

https://gitee.com/yedao2090/h2-o/tree/master/miniprogram

### Vant Weapp 版本

V1.11.1

### 描述一下你遇到的问题。

SystemError (jsEnginScriptError)
X(...).bem is not a function
TypeError: X(...).bem is not a function
at (appservice.app.js:439:36777)
at (common.app.js:1:30767)
at Object.C (appservice.app.js:439:36568)
at (@vant/weapp/field/index.appservice.js:1:2797)
at t.handleChildrenCreation (common.app.js:1:30528)
at (common.app.js:1:31877)
at (@vant/weapp/field/index.appservice.js:1:2703)
at t.handleChildrenCreation (common.app.js:1:30528)
at (common.app.js:1:30777)
at (@vant/weapp/field/index.appservice.js:1:2261)

### 重现步骤

必现：
1、采用基础库 3.2.2 
2、一点击带有 van-field 组件的界面就会有这个问题。

**Comment by TallNutAlt** [comment]
同样遇到了这个问题

**Comment by TallNutAlt** [comment]
@tech-insq {
    "renderer": "webview", // 修改渲染方式
    // "lazyCodeLoading": "requiredComponents", // 去除该代码
}

**Comment by johnsonwong666** [comment]
改用webview模式渲染。

**Comment by tech-insq** [comment]
我想问题是：我在 npm 安装vant weapp之后，少了一步npm install。 今天执行了这一步，重新编译就没有问题。
