### ISSUE TITLE
van-area  组件初始化报错

### ISSUE THREAD

**Issue by secreter** [youzan/vant-weapp#640]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
mpvue 上按照实例引用可以正常显示，但控制台报错

mpvue代码
```
<van-area :area-list="areaList" value="110101" />

import areaList from './area'
data () {
    return {
      areaList
    }
  }
```
报错信息
```
VM9317:1 thirdScriptError
Cannot read property 'county_list' of null; [Component] Property Observer Error @ static/vant/area/index#(anonymous)
TypeError: Cannot read property 'county_list' of null
    at c.setValues (http://127.0.0.1:61061/appservice/static/vant/area/index.js:126:61)
    at c.observer (http://127.0.0.1:61061/appservice/static/vant/area/index.js:32:14)
    at c.prop.observer (http://127.0.0.1:61061/appservice/static/vant/mixins/observer/props.js:26:18)
    at Function.r.safeCallback (http://127.0.0.1:61061/appservice/__dev__/WAService.js:17:14483)
    at a.<anonymous> (http://127.0.0.1:61061/appservice/__dev__/WAService.js:18:13674)
    at d (http://127.0.0.1:61061/appservice/__dev__/WAService.js:17:23079)
    at i.doUpdates (http://127.0.0.1:61061/appservice/__dev__/WAService.js:17:24291)
    at o.applyProperties (http://127.0.0.1:61061/appservice/__dev__/WAService.js:20:9672)
    at e.value (http://127.0.0.1:61061/appservice/__dev__/WAService.js:20:2387)
    at http://127.0.0.1:61061/appservice/__dev__/WAService.js:20:2459
console.error @ VM9317:1
errorReport @ WAService.js:3
thirdErrorReport @ WAService.js:3
(anonymous) @ WAService.js:3
(anonymous) @ WAService.js:19
r.safeCallback @ WAService.js:17
r.call @ WAService.js:17
a @ WAService.js:17
r.safeCallback @ WAService.js:17
(anonymous) @ WAService.js:18
d @ WAService.js:17
i.doUpdates @ WAService.js:17
o.applyProperties @ WAService.js:20
value @ WAService.js:20
(anonymous) @ WAService.js:20
value @ WAService.js:20
(anonymous) @ WAService.js:20
value @ WAService.js:20
(anonymous) @ WAService.js:20
value @ WAService.js:20
value @ WAService.js:19
p._advancedCreate @ WAService.js:18
p.create @ WAService.js:18
se @ WAService.js:19
a.addView @ WAService.js:19
value @ WAService.js:22
X @ WAService.js:21
re @ WAService.js:21
ie @ WAService.js:21
(anonymous) @ WAService.js:21
(anonymous) @ WAService.js:21
s.emit @ WAService.js:6
emit @ WAService.js:6
(anonymous) @ WAService.js:6
(anonymous) @ WAService.js:5
e @ appservice?t=1537890298907:6793
n.registerCallback.t @ appservice?t=1537890298907:6793
l.forEach.t @ appservice?t=1537890298907:6793
(anonymous) @ appservice?t=1537890298907:6793
i.onmessage @ appservice?t=1537890298907:6793
VM9317:1 thirdScriptError
Cannot read property 'province_list' of null; [Component] Property Observer Error @ static/vant/area/index#(anonymous)
TypeError: Cannot read property 'province_list' of null
    at c.getList (http://127.0.0.1:61061/appservice/static/vant/area/index.js:96:42)
    at c.setValues (http://127.0.0.1:61061/appservice/static/vant/area/index.js:127:27)
    at c.observer (http://127.0.0.1:61061/appservice/static/vant/area/index.js:11:14)
    at c.prop.observer (http://127.0.0.1:61061/appservice/static/vant/mixins/observer/props.js:26:18)
    at Function.r.safeCallback (http://127.0.0.1:61061/appservice/__dev__/WAService.js:17:14483)
    at a.<anonymous> (http://127.0.0.1:61061/appservice/__dev__/WAService.js:18:13674)
    at d (http://127.0.0.1:61061/appservice/__dev__/WAService.js:17:23079)
    at i.doUpdates (http://127.0.0.1:61061/appservice/__dev__/WAService.js:17:24291)
    at o.applyProperties (http://127.0.0.1:61061/appservice/__dev__/WAService.js:20:9672)
    at e.value (http://127.0.0.1:61061/appservice/__dev__/WAService.js:20:2387)
```

**环境**
 - 设备: win10小程序开发工具和手机上
 - 基础库版本: 2.21
 - Vant Weapp 版本:0.3.3

**Comment by chenjiahan** [comment]
请确认你的 areaList 是否正确传入

**Comment by jerryachel** [comment]
遇到同样的问题，mounted中可以打印出areaList 了

**Comment by vopdoo** [comment]
@secreter @jerryachel 
这个问题你们解决了没有呢 或者有没有解决思路
我也碰到一样的重现，界面已经展现出来了，但无法选择及取消 确定操作
