### ISSUE TITLE
Component is not found in path "miniprogram_npm/vant-weapp/button/index" (using by "pages/index/index")

### ISSUE THREAD

**Issue by fainle** [youzan/vant-weapp#674]
**描述一下问题**
Component is not found in path "miniprogram_npm/vant-weapp/button/index" (using by "pages/index/index")
Error: Component is not found in path "miniprogram_npm/vant-weapp/button/index" (using by "pages/index/index")
    at e (http://127.0.0.1:28546/appservice/__dev__/WAService.js:17:21187)
    at e (http://127.0.0.1:28546/appservice/__dev__/WAService.js:17:21373)
    at le (http://127.0.0.1:28546/appservice/__dev__/WAService.js:17:31774)
    at Object.i.addView (http://127.0.0.1:28546/appservice/__dev__/WAService.js:18:1197)
    at Function.value (http://127.0.0.1:28546/appservice/__dev__/WAService.js:20:180)
    at Xt (http://127.0.0.1:28546/appservice/__dev__/WAService.js:20:14547)
    at sn (http://127.0.0.1:28546/appservice/__dev__/WAService.js:20:17136)
    at un (http://127.0.0.1:28546/appservice/__dev__/WAService.js:20:17474)
    at Function.<anonymous> (http://127.0.0.1:28546/appservice/__dev__/WAService.js:20:19907)
    at L.<anonymous> (http://127.0.0.1:28546/appservice/__dev__/WAService.js:19:18084)

**环境**
 - 设备: 
 - 基础库版本: 2.3.0
 - Vant Weapp 版本: 0.3.4

**Comment by nikolausliu** [comment]
我也遇到了这个问题，请问解决了嘛
